config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root to: 'welcome#index'

  resources :apartments
  resources :users
  resources :expenses

  post '/invite_roommate' => 'users#invite_roommate'

  patch '/accept_invite' => 'users#accept_invite'
  post '/decline_invite' => 'users#decline_invite'

  delete '/clean_slate' =>'apartments#clean_slate'

end

app/models/apartment.rb
class Apartment < ActiveRecord::Base
  has_many :users
  has_many :expenses, through: :users

  def get_total
    if self.expenses.empty?
      0
    else
      self.expenses.map {|expense| expense.amount}.reduce(:+)
    end
  end

  def roommate_sums
    users = self.users
    apartment_total = self.get_total
    apartment_average = (apartment_total / users.length)
    roommate_sums = []
    users.each do |user|
      total = user.expenses.map {|expense| expense.amount}.reduce(:+) || 0
      balance = apartment_average - total
      roommate_sums << {:total => total, :balance => balance, :user => user}
    end
    return roommate_sums
  end

  def clean_slate
   expenses = self.expenses
   expenses.each do |expense|
     expense.delete
   end
  end

end

app/models/expense.rb
class Expense < ActiveRecord::Base
  belongs_to :user
  belongs_to :apartment
end

app/models/roommate.rb
class Roommate < ActiveRecord::Base
  belongs_to :user
  belongs_to :apartment
  has_many :expenses
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :apartment
  has_many :expenses
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :set_post, only: [:show, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def new
    @apartment = Apartment.new
  end

  def create
    @apartment = Apartment.new(apartment_params)
    if current_user.update(apartment: @apartment)
      redirect_to apartment_path (@apartment)
    end
  end

  def show

  end

  def edit

  end

  def update
    if @apartment.update(apartment_params)
      flash[:notice] = "You have successfully update this apartment."
    end
    redirect_to apartment_path(@apartment)
  end

  def destroy
    @apartment.destroy
    redirect_to apartment_path
  end

  def clean_slate
    @apartment = current_user.apartment
    @apartment.clean_slate
    redirect_to apartment_path(@apartment)
  end

  private
    def apartment_params
      params.require(:apartment).permit(:name)
    end

    def set_post
      @apartment = Apartment.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    authenticate_user!
    @user = current_user
    if current_user
      @expenses = current_user.expenses
    else
      redirect_to new_user_session_path
    end
  end

  def show
  end

  def new
      @roommate = current_user.first_name
      @expense = Expense.new
  end

  def create
      @apartment = current_user.apartment
      current_user.expenses.create(expense_params)
      redirect_to apartment_path(@apartment), notice: "This expense was successfully created!"
  end

  def edit
    @user = current_user
  end

  def update
    @apartment = current_user.apartment
    @user = current_user
    @expense.update(expense_params.merge(user: current_user))
    if @expense.update(expense_params)
      flash[:notice] = "You have successfully update this expense"
    end
    redirect_to apartment_path(@apartment)
  end

  def destroy
    @apartment = current_user.apartment
    @expense.destroy
    redirect_to apartment_path(@apartment)
  end

  private
  def expense_params
    params.require(:expense).permit(:created_at, :amount, :description, :user_first_name)
  end

  def set_post
    @expense = Expense.find(params[:id])
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]


  def index
    @expenses = current_user.expenses
    apartment_id = current_user.temp_id
    @apartment = Apartment.find_by(apartment_id params[:id])
  end

  def new
    @user = User.new
  end

  def create

  end

  def show
    temp_id = current_user.temp_id
    apartment = Apartment.where(params[:id] == temp_id)
    @apartment = apartment.name
    @user = current_user.first_name
  end

  def update
    @apartment = current_user.apartment.name
    if current_user.apartment_id
      redirect_to apartment_path(@apartment)
    end
  end

  def invite_roommate
    user = User.find_by(email: params[:email])
    @apartment = current_user.apartment_id
    if user
      user.temp_id = current_user.apartment_id
      user.save
      redirect_to apartment_path(@apartment), notice: "You have successfully invited this roommate. Your roommate must log-in to accept or decline your invitation."
    else
      redirect_to apartment_path(@apartment), notice: "This email address was not found. Please ask your roommate to create an account on Clean Slate before you request to add them as a roommate."
    end
  end

  def accept_invite
    current_user.apartment_id = current_user.temp_id
    current_user.save
    current_user.temp_id = nil
    current_user.save
    redirect_to apartment_path(current_user.apartment), notice: "You have successfully joined as a roommate!"
  end

  def decline_invite
    redirect_to new_apartment_path
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :encrypted_password, :temp_id)
  end

  def set_post
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    authenticate_user!
    if current_user.apartment_id
      redirect_to apartment_path(current_user.apartment)
    elsif current_user.temp_id
      redirect_to user_path(current_user)
    else
      render :index
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/apartments/edit.html.erb
<h2>Update Apartment</h2>

<%= form_for ([current_user.apartment]) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>

<% end %>

app/views/apartments/new.html.erb
<h2>Register:</h2>

<p class="subtitle">Create a profile for your house or apartment so that you can invite your roommates to join your account on Clean Slate, and start tracking your household expenses!</p>


<%= form_for ([@apartment]) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>

<% end %>

<%= image_tag("kitchen.jpg", class: "image") %>

app/views/apartments/show.html.erb
<h1><%= @apartment.name %></h1>
<button><%= link_to "Update Apartment", edit_apartment_path(@apartment) %></button>

<h2 class='subtitle'>Roommates:</h2>
  <% @apartment.users.each do |roommate| %>
  <p class='subtitle'><%= roommate.first_name %></p>
  <% end %>

<button><%= link_to "Invite Roommates", new_user_path %></button>


<div class="expenses">
  <h2 class='subtitle'>This Month's Expenses:</h2>
  <button><%= link_to "New expense (+)", new_expense_path(current_user) %></button>


  <% @apartment.users.each do |roommate| %>
    <table class="center">
      <thead>
        <tr>
          <th>Date</th>
          <th>Description</th>
          <th>Amount</th>
          <th>Roommate</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% roommate.expenses.each do |expense| %>
        <tr>
          <td><%= expense.created_at.strftime("%m/%d/%y") %></td>
          <td><%= expense.description %></td>
          <td><%= expense.amount %></td>
          <td><%= expense.user.first_name %></td>
          <td><%= link_to "Edit", edit_expense_path(expense) %></td>
          <td><%= link_to "Remove", expense, method: :delete, data: { confirm: "Are you sure?" } %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  <br>
  <% end %>
  <br>
</div>

<h2 class='subtitle'>Settle Up:</h2>
<table class="center">
  <thead>
    <tr>
      <th>Roommate</th>
      <th>Total Spent</th>
      <th>Balance</th>
    </tr>
  </thead>
  <tbody>
    <% @apartment.roommate_sums.each do |sum| %>
    <tr>
      <td><%= sum[:user].first_name %></td>
      <td><%= sum[:total] %></td>
      <td><%= sum[:balance] %></td>
    </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td>Total Spent:</td>
      <td><%= @apartment.get_total %></td>
      <td>0</td>
    </tr>
  </tfoot>
</table>

<button>
  <%= link_to "All Paid up? Click Here for a Clean Slate", clean_slate_path, method: :delete, data: { confirm: "Are you sure?" } %>
</button>

<div class ="center">
<%= image_tag("bills.jpg", class: "image") %>
</div>

<br>

app/views/expenses/_form.html.erb
<%= form_for [@expense] do |f| %>

  <%= f.label :amount %>
  <%= f.text_field :amount %>

  <%= f.label :description %>
  <%= f.text_field :description %>



  <%= f.submit %>

<% end %>

app/views/expenses/_table.html.erb
<table class="center">
  <thead>
    <tr>
      <th>Date</th>
      <th>Description</th>
      <th>Amount</th>
      <th>Roommate</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @expenses.each do |expense| %>
    <tr>
      <td><%= expense.created_at.strftime("%b, %d, %y") %></td>
      <td><%= expense.description %></td>
      <td><%= expense.amount %></td>
      <td><%= expense.user.first_name %></td>
      <td><%= link_to "Edit", edit_expense_path(expense) %></td>
      <td><%= link_to "Remove", expense, method: :delete, data: { confirm: "Are you sure?" } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/expenses/edit.html.erb
<h2>Update Expense</h2>

<%= render "form" %>

<div class ="center">
<%= image_tag("cup.jpg", class: "image") %>
</div>

app/views/expenses/index.html.erb
<!-- can delete file if not being used -->

app/views/expenses/new.html.erb
<h2>Enter New Expense</h2>

<%= render "form" %>

<div class ="center">
<%= image_tag("cup.jpg", class: "image") %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CleanSlate</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Montserrat:700|Architects+Daughter|Gudea' rel='stylesheet' type='text/css'>
</head>
<body>

<nav>
  <div class="user-info login">
    <h1 class="white">Welcome to Clean Slate:</h2>
    <p>
     <% if current_user %>
      You are logged in as <%= current_user.first_name %>
       <%= link_to 'Signout', destroy_user_session_path, :method => :delete %>
     <% else %>
       <%= link_to 'Signup', new_user_registration_path %>
       <%= link_to 'Login', new_user_session_path %>
     <% end %>
     </p>
  </div>
</nav>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
<footer>
  <nav>
    <p class='foot'>Clean Slate: Preventing Roommate Squabbles since 2015</p>
</footer>
<div class='foot_image'>
  <%= image_tag("couch.jpg", class: "cover") %>
</div>
</html>

app/views/users/_form.html.erb
<p class="subtitle">Invite a roommate by entering the email address they used when signing up for an account on Clean Slate: </p>
<form action="/invite_roommate" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type= "text" name= "email" >
  <input type= "submit">
</form>

app/views/users/edit.html.erb
<h2>Update Roommate Profile</h2>

<%= render "form" %>

app/views/users/index.html.erb
<h1><%= "#{@user}" %></h1>

<h2 class="subtitle"><%= @apartment.name %> has invited you to join their account on Clean Slate.</h2>
<h2 class="subtitle">Would you like to join?</h2>


<button class="subtitle"><%= link_to "Accept Invitation", apartment_path(@apartment) %></button>

<button class="subtitle"><%= link_to "Decline Invitation", new_apartment_path %></button>

app/views/users/new.html.erb
<h2>Add a Roommate</h2>
<p class="subtitle">Note: Please ask your roommate to sign-up for a user account before you add them as a roommate here.</p>

<p class="subtitle">(but they should not create an apartment profile)</p>

<%= render "form" %>

app/views/users/show.html.erb
<h1><%= "#{@user}" %></h1>

<h2 class="subtitle"><%= "#{@apartment}" %> has invited you to join their account on Clean Slate.</h2>
<h2 class="subtitle">Would you like to join?</h2>


<button>
  <%= link_to "Accept Invitation", accept_invite_path, method: :patch %>
</button>

<button>
  <%= link_to "Decline Invitation", decline_invite_path, method: :patch %>
</button>

app/views/welcome/index.html.erb
<h1>Clean Slate</h1>
<h2 class='subtitle'>Get even with your roommates and live happily ever after.</h2>
<h2 class='subtitle'> An app for settling your accounts.</h2>

<% if current_user.temp_id %>
  <h2><%= link_to "Confirm Profile Information", users_path(current_user) %></h2>

<% elsif current_user %>
  <h2><%= link_to "Create Your Apartment", new_apartment_path %></h2>

<% else %>

  <%= link to "Sign in or Create an Account", new_user_session_path %>

<% end %>

<%= image_tag("cup.jpg", class: "image") %>